# Generated by Django 4.2.7 on 2026-03-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_student_roll_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text="Student's profile photo", null=True, upload_to='student_photos/%Y/%m/'),
        ),
    ]
