# Generated by Django 4.2.7 on 2026-03-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_student_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='absencerecord',
            name='parent_approval',
            field=models.BooleanField(default=None, help_text='Parent decision for leave approval', null=True),
        ),
        migrations.AddField(
            model_name='absencerecord',
            name='parent_response_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when parent responded', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(blank=True, help_text='Parent WhatsApp phone number', max_length=15, null=True),
        ),
    ]
