# Generated by Django 4.2.7 on 2026-03-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_absencerecord_parent_approval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestrequest',
            name='qr_generated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when guest QR token was generated', null=True),
        ),
        migrations.AddField(
            model_name='guestrequest',
            name='qr_token',
            field=models.CharField(blank=True, help_text='Generated token used to render guest QR', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='guestrequest',
            name='visit_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('overnight', 'Overnight')], default='normal', help_text='Normal visits are auto-approved; overnight visits require warden approval', max_length=20),
        ),
    ]
