# Generated by Django 4.2.7 on 2026-03-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_guestrequest_visit_type_and_qr_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestrequest',
            name='qr_image_path',
            field=models.CharField(blank=True, help_text='Path to generated QR image file', max_length=255, null=True),
        ),
    ]
