# Generated by Django 4.2.7 on 2026-04-05 17:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_guestrequest_qr_image_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(help_text='Title of the notice', max_length=200)),
                ('content', models.TextField(help_text='Detailed content of the notice')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Priority level of the notice', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the notice is currently active/visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warden', models.ForeignKey(help_text='Staff member who posted the notice', on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='core.staff')),
            ],
            options={
                'db_table': 'notice_board',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', '-created_at'], name='notice_boar_is_acti_012005_idx')],
            },
        ),
    ]
