# Generated by Django 4.2.23 on 2026-04-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_noticeboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='photo',
            field=models.ImageField(blank=True, help_text='Optional photo attached by student for maintenance issue', null=True, upload_to='maintenance_photos/%Y/%m/'),
        ),
    ]
