# Generated by Django 4.2.7 on 2026-04-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_maintenancerequest_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('warden', 'Warden'), ('security', 'Security'), ('admin', 'Administrator'), ('maintenance_head', 'Maintenance Head'), ('maintenance_staff', 'Maintenance Staff'), ('maintenance', 'Maintenance')], help_text='Staff role/position', max_length=20),
        ),
    ]
