# Generated by Django 4.2.7 on 2026-04-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_staff_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='photo',
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('warden', 'Warden'), ('security', 'Security'), ('admin', 'Administrator'), ('maintenance', 'Maintenance')], help_text='Staff role/position', max_length=20),
        ),
    ]
