# Generated by Django 4.2.7 on 2026-04-07 09:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_maintenancerequest_photo_alter_staff_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('message', models.TextField(help_text='Notification message')),
                ('type', models.CharField(help_text='Type of notification (leave, guest, notice, maintenance, security, etc.)', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='Priority level of the notification', max_length=20)),
                ('action_url', models.CharField(blank=True, help_text='URL to navigate to when notification is clicked', max_length=500, null=True)),
                ('metadata', models.JSONField(default=dict, help_text='Additional context data (e.g., request_id, approval_type)')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the notification has been read')),
                ('read_at', models.DateTimeField(blank=True, help_text='Timestamp when notification was read', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient_staff', models.ForeignKey(blank=True, help_text='Staff recipient of the notification', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_received', to='core.staff')),
                ('recipient_student', models.ForeignKey(blank=True, help_text='Student recipient of the notification', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_received', to='core.student')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient_student', 'is_read', '-created_at'], name='notificatio_recipie_036d93_idx'), models.Index(fields=['recipient_staff', 'is_read', '-created_at'], name='notificatio_recipie_c76709_idx')],
            },
        ),
    ]
