# Generated by Django 4.2.7 on 2026-04-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticeboard',
            name='target_audience',
            field=models.CharField(
                choices=[('student', 'Student'), ('security', 'Security')],
                default='student',
                help_text='Which dashboard should receive this notice',
                max_length=20,
            ),
        ),
    ]
