# Generated by Django 4.2.7 on 2026-04-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_noticeboard_target_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_first_login',
            field=models.BooleanField(default=False, help_text='Whether this is the first login'),
        ),
    ]
