# Generated by Django 4.2.7 on 2026-04-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_staff_is_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='attachment',
            field=models.ImageField(blank=True, help_text='Optional photo from the student showing the issue', null=True, upload_to='maintenance/%Y/%m/'),
        ),
    ]
